name: Build & Run tests

on:
  push:
  workflow_dispatch:

jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install SDL3 dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev libpulse-dev libaudio-dev libjack-dev libsndio-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxinerama-dev libxss-dev libwayland-dev libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev

      - name: Build Project
        uses: threeal/cmake-action@v2.1.0
        with:
          source-dir: .
          build-dir: build
          build-type: Release
          args: -DBUILD_TESTS=ON

      - name: Run Tests
        run: |
          ./build/RealEngine_tests